### ISSUE TITLE
no Understand in java.library.path

### ISSUE THREAD

**Issue by tdurieux** [justinwm/CapGen#3]
Hello @justinwm ,

I try to run CapGen on Defects4j but I face this error. Can you give additional information on how to set up the environment? Thank you

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: no Understand in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.scitools.understand.Understand.loadNativeLibrary(Understand.java:96)
	at com.scitools.understand.Understand.open(Understand.java:46)
	at org.capgen.util.AnalyzeUnderstand.extractCFG(AnalyzeUnderstand.java:102)
	at org.capgen.main.ExtractSemanticFeature.extractSemanticInfo(ExtractSemanticFeature.java:249)
	at org.capgen.main.ExtractSemanticFeature.generateSemanticFiles(ExtractSemanticFeature.java:72)
	at org.capgen.main.Main.runCapGen(Main.java:229)
	at org.capgen.main.Main.main(Main.java:337)
```

**Comment by MingWEN-CS** [comment]
Hi

As I mentioned in the Paper and the documentation, CapGen relies on the tool Understand for semantic analysis. 

Installation could be found at https://scitools.com/support/linux-solaris-install/

Thanks very much for your interests :-)

**Comment by tdurieux** [comment]
You mention some documentation, where is it? Thank you

**Comment by tdurieux** [comment]
By the way you mention in your paper:

> The implementation of CapGen and the details of our evaluation results are publicly available at:

Where can I found the implementation?  I was only able to find the binaries.

**Comment by MingWEN-CS** [comment]
> You mention some documentation, where is it? Thank you

The last paragraph in this page. https://github.com/justinwm/CapGen/tree/master/Defects4J.

Yes, currently, we only provided the binary file.

**Comment by tdurieux** [comment]
Ok

Which version of Understand do you use because I have the following error?

```java
Using Configuration File:	config_local.txt
== Start locating the faults
The fault space has already been generated in 	./Chart_1_buggy/faultSpace/originalTest.txt
== Finish locating the faults
== Start extracting the ingredients
Processing File:	./Chart_1_buggy/source/org/jfree/chart/renderer/category/AbstractCategoryItemRenderer.java
./Chart_1_buggy/source/org/jfree/chart/renderer/category/AbstractCategoryItemRenderer.java
ClassPath:	./Chart_1_buggy/source
./Chart_1_buggy/source/org/jfree/chart/renderer/category/AbstractCategoryItemRenderer.java
Processing File:	./Chart_1_buggy/source/org/jfree/chart/renderer/category/LineAndShapeRenderer.java
./Chart_1_buggy/source/org/jfree/chart/renderer/category/LineAndShapeRenderer.java
ClassPath:	./Chart_1_buggy/source
./Chart_1_buggy/source/org/jfree/chart/renderer/category/LineAndShapeRenderer.java

./Chart_1_buggy/source//org/jfree/chart/renderer/category/LineAndShapeRenderer.java
ClassPath:	./Chart_1_buggy/source/
./Chart_1_buggy/source//org/jfree/chart/renderer/category/AbstractCategoryItemRenderer.java
ClassPath:	./Chart_1_buggy/source/
begin to analyze by understand tool
und create -db /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/ingredients/LineAndShapeRenderer.java.udb -languages java 
Error:und create -db /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/ingredients/LineAndShapeRenderer.java.udb -languages java 
und -db /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/ingredients/LineAndShapeRenderer.java.udb add /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/source/org/jfree/chart/renderer/category/LineAndShapeRenderer.java 
Error:und -db /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/ingredients/LineAndShapeRenderer.java.udb add /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/source/org/jfree/chart/renderer/category/LineAndShapeRenderer.java 
Error:und -db /tmp/CapGen_Defects4J_Chart_1/./Chart_1_buggy/ingredients/LineAndShapeRenderer.java.udb analyze
Exception in thread "main" com.scitools.understand.UnderstandException: DBUnableOpen
	at com.scitools.understand.Understand.openDatabase(Native Method)
	at com.scitools.understand.Understand.open(Understand.java:49)
	at org.capgen.util.AnalyzeUnderstand.extractCFG(AnalyzeUnderstand.java:102)
	at org.capgen.main.ExtractSemanticFeature.extractSemanticInfo(ExtractSemanticFeature.java:249)
	at org.capgen.main.ExtractSemanticFeature.generateSemanticFiles(ExtractSemanticFeature.java:72)
	at org.capgen.main.Main.runCapGen(Main.java:229)
	at org.capgen.main.Main.main(Main.java:337)
```

**Comment by tdurieux** [comment]
I succeed to setup the tool but I don't succeed to generate patches.
It seems the ranking of the ingredients is always 0:
`434	org.jfree.chart.renderer.category.AbstractCategoryItemRenderer::::1796::::66566::::66570::::index::::i	0.0` (ranked first for Char-1 in the provided data)
Do you know what can cause this issue?

Thank you

**Comment by Dearth** [comment]
Hello, I have run in to the above problem even after adding Understand.jar to the classpath.  Does the CapGen.jar require an older version of Understand or am I invoking this incorrectly?

Command: `java -cp .:/path/to/Understand.jar -jar CapGen.jar configuration_file`

CapGen runs as expected until it hits the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no Understand in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.scitools.understand.Understand.loadNativeLibrary(Understand.java:96)
	at com.scitools.understand.Understand.open(Understand.java:46)
	at org.capgen.util.AnalyzeUnderstand.extractCFG(AnalyzeUnderstand.java:102)
	at org.capgen.main.ExtractSemanticFeature.extractSemanticInfo(ExtractSemanticFeature.java:249)
	at org.capgen.main.ExtractSemanticFeature.generateSemanticFiles(ExtractSemanticFeature.java:72)
	at org.capgen.main.Main.runCapGen(Main.java:229)
	at org.capgen.main.Main.main(Main.java:351)
```



Any help is appreciated.  

Thanks,
Dearth
